# Generated by Django 6.0.1 on 2026-01-29 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='法人名')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='法人コード')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '法人',
                'verbose_name_plural': '法人一覧',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='施設名')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='施設コード')),
                ('is_active', models.BooleanField(default=True, verbose_name='契約中')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company', verbose_name='所属法人')),
            ],
            options={
                'verbose_name': '施設',
                'verbose_name_plural': '施設一覧',
            },
        ),
    ]
