# Generated by Django 5.2.9 on 2026-01-31 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='利用者名')),
                ('name_kana', models.CharField(blank=True, max_length=100, verbose_name='カナ氏名')),
                ('insured_number', models.CharField(blank=True, max_length=20, verbose_name='被保険者番号')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company', verbose_name='所属法人')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.facility', verbose_name='利用施設')),
            ],
            options={
                'verbose_name': '介護利用者',
                'verbose_name_plural': '利用者マスタ',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', '管理者'), ('MANAGER', '施設長'), ('STAFF', '一般職員'), ('PART', 'パート・アルバイト')], default='STAFF', max_length=20, verbose_name='権限ロール')),
                ('joined_at', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company', verbose_name='所属法人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー')),
            ],
            options={
                'verbose_name': '職員情報',
                'verbose_name_plural': '職員管理',
            },
        ),
    ]
