# Generated by Django 6.0.1 on 2026-01-29 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='ファイル')),
                ('doc_type', models.CharField(choices=[('RECEIPT', 'レシート・領収書'), ('INVOICE', '請求書'), ('CONTRACT', '契約書'), ('REPORT', '日報・介護記録'), ('SALARY', '給与明細'), ('OTHER', 'その他')], max_length=20, verbose_name='文書タイプ')),
                ('status', models.CharField(choices=[('PENDING', '解析待ち'), ('PROCESSING', 'AI解析中'), ('CONFIRMED', '確認済み'), ('APPROVED', '承認完了')], default='PENDING', max_length=20, verbose_name='ステータス')),
                ('ai_data', models.JSONField(blank=True, default=dict, verbose_name='AI解析データ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.company', verbose_name='法人')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.facility', verbose_name='施設')),
            ],
            options={
                'verbose_name': 'ドキュメント',
                'verbose_name_plural': 'ドキュメント一覧',
            },
        ),
    ]
